#!/usr/bin/env ruby
#^syntax detection

site 'http://community.opscode.com/api/v1'

cookbook 'apt'
cookbook 'apt-repo'
cookbook 'build-essential'
cookbook 'ntp'
cookbook 'redisio',
  :git => 'https://github.com/brianbianco/redisio'
